apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-service
  namespace: store-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-service
  template:
    metadata:
      labels:
        app: exchange-service
    spec:
      containers:
        - name: exchange-service
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

