apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  namespace: store-platform
data:
  SPRING_APPLICATION_NAME: account-service
  SERVER_PORT: "8083"
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_DB: store
  DATABASE_USERNAME: store
  SPRING_JPA_OPEN_IN_VIEW: "false"
