apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: store-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: account-service-config
            - secretRef:
                name: account-service-secret
          ports:
            - containerPort: 8083
          readinessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 40
            periodSeconds: 20
