apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: store-platform
spec:
  selector:
    app: account-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
