apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: store-platform
data:
  SPRING_APPLICATION_NAME: order-service
  SERVER_PORT: "8081"
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_DB: store
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  SPRING_JPA_OPEN_IN_VIEW: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: orders
  SPRING_FLYWAY_ENABLED: "true"
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
  SPRING_FLYWAY_SCHEMAS: orders
  SPRING_FLYWAY_DEFAULT_SCHEMA: orders
  PRODUCT_SERVICE_URL: http://product-service:8080
  EXCHANGE_SERVICE_URL: http://exchange-service:8000
