apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: store-platform
data:
  SPRING_APPLICATION_NAME: order-service
  SERVER_PORT: "8081"
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_DB: store
  DATABASE_USERNAME: store
  PRODUCT_SERVICE_URL: http://product-service:8080
  EXCHANGE_SERVICE_URL: http://exchange-service:8000
  SPRING_JPA_OPEN_IN_VIEW: "false"
