apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: store-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: auth-service-config
            - secretRef:
                name: auth-service-secret
          ports:
            - containerPort: 8084
          readinessProbe:
            httpGet:
              path: /auth/
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /auth/
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 20
