apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: store-platform
data:
  SPRING_APPLICATION_NAME: product-service
  SERVER_PORT: "8080"
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_DB: store
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  SPRING_JPA_OPEN_IN_VIEW: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: products
  SPRING_FLYWAY_ENABLED: "true"
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
  SPRING_FLYWAY_SCHEMAS: products
  SPRING_FLYWAY_DEFAULT_SCHEMA: products
  SPRING_CACHE_TYPE: redis
  REDIS_HOST: redis
  REDIS_PORT: "6379"
