apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
  namespace: store-platform
data:
  SPRING_APPLICATION_NAME: gateway-service
  SERVER_PORT: "8085"
  CLIENTS_ACCOUNT_SERVICE_URL: http://account-service:8083
  CLIENTS_AUTH_SERVICE_URL: http://auth-service:8084
  CLIENTS_PRODUCT_SERVICE_URL: http://product-service:8080
  CLIENTS_ORDER_SERVICE_URL: http://order-service:8081
  CLIENTS_EXCHANGE_SERVICE_URL: http://exchange-service:8000
  GATEWAY_AUTH_SOLVE_URL: http://auth-service:8084/auth/solve
