apiVersion: v1
kind: ConfigMap
metadata:
  name: exchange-service-config
  namespace: store-platform
data:
  AWESOME_API_BASE_URL: https://economia.awesomeapi.com.br/json/last
  AWESOME_API_TIMEOUT_SECONDS: "5"
